# Generated by Django 4.2 on 2023-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
